mybatis:
  mapper-locations: classpath:mybaties/mapper/*.xml
  type-aliases-package: com.example.demo.model
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    validationQuery: select 'x'
    quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: DefaultQuartzScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
              isClustered: false
              clusterCheckinInterval: 10000
              useProperties: true
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
            dataSource:
              default:
                URL: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8
                user: root
                password: root
                driver: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    listener:
      simple:
        auto-startup: true
        concurrency: 10
        default-requeue-rejected: true
        max-concurrency: 10
        prefetch: 1
    password: guest
    port: 5672
    template:
      retry:
        enabled: 'true '
        max-attempts: 3
        multiplier: 1.0
    username: guest
    virtual-host: /
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
    password: ''
    port: 6379
